


# Usa una imagen oficial de Node.js como base
FROM node:18

# Crea y define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todo el código fuente al contenedor
COPY . .

# Expone el puerto utilizado por tu aplicación
EXPOSE 6010

# Define el comando para iniciar la aplicación
CMD ["npm", "start"]
